name: Run scraper
on:
    workflow_dispatch:
    schedule:
        #9:00am everyday
        - cron: "0 9 * * *"

jobs:
    Scrape:
        #setting virtual env to the latest ver of Ubuntu
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: "3.9"
            
            # - name: Install dependencies
            #   run: pip install requests beautifulsoup4
            
            #run the script
            - name: Run script
              run: python testing_time.py
                
            - name: Add and commit
              id: add_commit
              uses: EndBug/add-and-commit@v8
              with:
                committer_name: Automated
                committer_email: actions@users.noreply.github.com
                message: "Latest data"
            
            - name: Push	
              run: git push
